import fs from "fs";
import bs58 from "bs58";
import { Uploader } from "@irys/upload";
import { Solana } from "@irys/upload-solana";
import { config } from "./config.js";

// Uploads the generated image + metadata JSON to Arweave via Irys - the
// same service StonkFun/Raydium use for their own tokens (noticed from
// the "gateway.irys.xyz" URLs their API returns). It costs SOL, but each
// upload costs fractions of a cent for the image/JSON size we generate
// here.

let cachedUploader = null;

async function getUploader() {
  if (cachedUploader) return cachedUploader;
  const privateKeyBase58 = bs58.encode(config.walletKeypair.secretKey);
  cachedUploader = await Uploader(Solana).withWallet(privateKeyBase58);
  return cachedUploader;
}

// Tops up the Irys node only if the already-loaded balance is below this
// floor - avoids refunding (and wasting idle SOL there) on every call.
const MIN_BALANCE_LAMPORTS = 3_000_000; // 0.003 SOL
const TOP_UP_SOL = 0.01;

async function ensureFunded(uploader) {
  let currentBalance = 0;
  try {
    const balance = await uploader.getLoadedBalance();
    currentBalance = Number(balance.toString());
  } catch (err) {
    console.error("[arweaveUpload] couldn't read the Irys balance, will try to fund it anyway:", err.message);
  }

  if (currentBalance >= MIN_BALANCE_LAMPORTS) return;

  console.log(`[arweaveUpload] Irys balance low (${currentBalance} lamports) - funding with ${TOP_UP_SOL} SOL...`);
  await uploader.fund(uploader.utils.toAtomic(TOP_UP_SOL));
}

/**
 * Uploads the image (PNG already generated by imageGen.js) + a standard
 * metadata JSON (name/symbol/description/image) to Arweave. Returns both
 * permanent URLs - the metadata one is what goes in the token's "uri"
 * field (see tokenMinter.js).
 */
export async function uploadTokenAssets({ imagePath, name, symbol, description, contentType = "image/png" }) {
  const uploader = await getUploader();
  await ensureFunded(uploader);

  const imageBuffer = fs.readFileSync(imagePath);
  const imageReceipt = await uploader.upload(imageBuffer, {
    tags: [{ name: "Content-Type", value: contentType }],
  });
  const imageUrl = `https://gateway.irys.xyz/${imageReceipt.id}`;

  const metadata = { name, symbol, description, image: imageUrl };
  const metadataReceipt = await uploader.upload(JSON.stringify(metadata), {
    tags: [{ name: "Content-Type", value: "application/json" }],
  });
  const metadataUrl = `https://gateway.irys.xyz/${metadataReceipt.id}`;

  return { imageUrl, metadataUrl };
}
